# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f51acd9b89d9f43a4f561501c23524c8f496e3db8b00ea5e061e6bc1d1219873d1a6cd0022320f48928837acd7e08908710a80dece4da5691a98dea3f66fb11

test:
  secret_key_base: b02bacced3f8b7b321f002ea7faf708b4ace25ad1be7b848ab84c2e2a5cea6205422770d26b0c00f06a8348199085122e768f85dc3560fc6e62b1d4a02c7ee09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
